from mpi4py import MPI
import numpy as np

comm = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()

n = 1000000
localNInsideCircle = 0      #Number of points inside the circle generated by each processor
totalNInsideCircle = 0      #Total number of points inside the circle
localN = int(n/size)        #Number of points generated by each processor

for i in range(0, localN):
    x = np.random.random()
    y = np.random.random()
    if(x*x + y*y < 1):      #Checking if the point lies inside the circle
        localNInsideCircle += 1

totalNInsideCircle = comm.reduce(localNInsideCircle, MPI.SUM)       #Finding the total number of points inside the cicle
if(rank == 0):
    pi = 4*totalNInsideCircle/n
    print(pi)